### ISSUE TITLE
ee_install() fails,  Conda info could not be constructed

### ISSUE THREAD

**Issue by andreatitolo** [r-spatial/rgee#195]
* rgee version: 1.1.2
* R version: 4.1.2
* Operating System: MacOS Monterey 12.0.1

### Description

Hi Cesar, I was trying to initialize rgee using the command ``` ee_install()``` (I already have Anaconda installed on my system) and I got an error telling me that conda info could not be constructed and that reticulate did not find any python environment. If I choose to not install miniconda, the installation is aborted. 
I did the same thing on my windows computer with anaconda installed and I had no problem, so I am a bit lost here. This is my first time using MacOS, so if this is something related to my poor understanding of how it works, I apologize in advance.

### What I Did

```r
library(rgee)
regee::ee_install()

WARNING conda.exceptions:print_unexpected_error_report(1213): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/cli/main_create.py", line 41, in execute
    install(args, parser, 'create')
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/core/solve.py", line 262, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
    _supplement_index_with_system(virtual_pkg_index)
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
    cuda_version = context.cuda_version
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/common/decorators.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/base/context.py", line 849, in cuda_version
    return cuda_detect()
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/common/cuda.py", line 37, in cuda_detect
    import ctypes
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/andreatitolo/Library/r-miniconda/lib/python3.8/lib-dynload/_ctypes.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libffi.7.dylib
  Referenced from: /Users/andreatitolo/Library/r-miniconda/lib/python3.8/lib-dynload/_ctypes.cpython-38-darwin.so
  Reason: tried: '/Users/andreatitolo/Library/r-miniconda/lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/python3.8/lib-dynload/../../libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/python3.8/lib-dynload/../../libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/bin/../lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/bin/../lib/libffi.7.dylib' (no such file), '/usr/local/lib/libffi.7.dylib' (no such file), '/usr/lib/libffi.7.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/exceptions.py", line 1211, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/cli/main_info.py", line 237, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
        _supplement_index_with_system(virtual_pkg_index)
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/common/decorators.py", line 20, in wrapper
        return func(*args, **kwargs)
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/base/context.py", line 849, in cuda_version
        return cuda_detect()
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/site-packages/conda/common/cuda.py", line 37, in cuda_detect
        import ctypes
      File "/Users/andreatitolo/Library/r-miniconda/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/Users/andreatitolo/Library/r-miniconda/lib/python3.8/lib-dynload/_ctypes.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libffi.7.dylib
      Referenced from: /Users/andreatitolo/Library/r-miniconda/lib/python3.8/lib-dynload/_ctypes.cpython-38-darwin.so
      Reason: tried: '/Users/andreatitolo/Library/r-miniconda/lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/python3.8/lib-dynload/../../libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/python3.8/lib-dynload/../../libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/bin/../lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/lib/libffi.7.dylib' (no such file), '/Users/andreatitolo/Library/r-miniconda/bin/../lib/libffi.7.dylib' (no such file), '/usr/local/lib/libffi.7.dylib' (no such file), '/usr/lib/libffi.7.dylib' (no such file)

`$ /Users/andreatitolo/Library/r-miniconda/bin/conda create --yes --prefix /Users/andreatitolo/Library/r-miniconda/envs/r-reticulate python=3.6 numpy -c conda-forge`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
reticulate did not find any Python ENV on your system.
```

**Comment by csaybar** [comment]
Sorry, it looks like a problem with your conda env. Did you try to use virtualenv?

https://github.com/conda/conda/issues/9356

**Comment by andreatitolo** [comment]
Thanks! I didn't, using virtualenv did the trick! (mostly, I had to manually install python packages because some of them failed during the creation of the virtualenv using reticulate)
I am still convinced this is a mistake on my end somewhere, but in case it's useful for someone else:

- Completely removed Anaconda/Miniconda (unnecessary)
- Removed reticulate and rgee
- Reinstalled reticulate
- Pointed Rstudio to use Python 3.8 (following [here](https://www.rstudio.com/blog/rstudio-v1-4-preview-python-support/), because for some reason reticulate was pointing at Python 2.7 by default
- Created virtualenv,, got an error in building wheel for numpy
- Manually installed 'pip', 'wheel', 'setuptools', and 'numpy' in the virtualenv, everything worked
- Installed earthengine API in that virtualenv
- Point Rstudio to use the Python virtualenv just created
- Reinstalled rgee
- Used ```ee_install_set_pyenv("path/to/virtualenv/bin/python", "virtualenv")```
- Running ```ee_initialize(Drive = TRUE)```
- Tested and everything seems to work now!
